# This is a basic workflow to help you get started with Actions

name: Get info about my GCP bucket

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Get_my_OIDC_ID_token"
  Get_my_OIDC_ID_token:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v4
      
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    
    # Configure Worklaod Identity Federation and generate an access token  
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.SA_EMAIL }}'
          
    - id: 'gcloud'
      name: 'gcloud storage access'
      run: |-
        # gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        # gcloud storage ls gs://stef-actions-bucket-1
        #gcloud storage --project 'demowif' ls gs://stef-actions-bucket-1
        gcloud storage --project 'demowif' ls gs://stef-actions-bucket-1

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.

